# Generated by Django 3.2.8 on 2021-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='show',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
