# Generated by Django 3.2.8 on 2021-10-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
