# Generated by Django 3.2.8 on 2021-10-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
